sudo: required
dist: trusty
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  matrix:
    - PROJECT="tvt"
    - PROJECT="cs_gan"
    - PROJECT="iodine"
    - PROJECT="transporter"
    - PROJECT="polygen"
    - PROJECT="learning_to_simulate"
    - PROJECT="avae"
before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
script:
  - ./$PROJECT/run.sh

